# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Loadtest test.k6.io

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  loadtest:
    name: k6 local test run
    runs-on: ubuntu-latest
    container: docker://grafana/k6:0.38.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 local test - sample
        uses: k6io/action@v0.1
        with:
          filename: sample.js

      - name: Run k6 local test - example
        uses: k6io/action@v0.1
        with:
          filename: example.js
